#ifndef ADCANALYSIS_CONFIG_H
#define ADCANALYSIS_CONFIG_H




/* Defines */

#define ADCANALYSIS_NUMBER_OF_SAMPLES_FOR_BATTERY_VOLTAGE_VALUE 5
#define ADCANALYSIS_NUMBER_OF_SAMPLES_FOR_CAPACITOR_VOLTAGE_VALUE 5




#endif // ADCANALYSIS_CONFIG_H